name: CodeMask CI

on:
  push:
    branches: [ "main", "prod" ]
  pull_request:
    branches: [ "main", "prod" ]

jobs:
  test:
    name: Build and Test
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
      
    - name: Run Tests
      run: |
        xcodebuild test \
          -project CodeMask/CodeMask.xcodeproj \
          -scheme CodeMask \
          -destination 'platform=macOS' \
          -enableCodeCoverage YES \
          -skip-testing CodeMaskUITests \
          CODE_SIGNING_ALLOWED=NO